version: '3'

services:
  django: &django
    build:
      context: .
      dockerfile: Dockerfile
    image: acme_local_django
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    command: /start
